### ISSUE TITLE
Project goal

### ISSUE THREAD

**Issue by Cyberzoid1** [CS383Team2/CS383Stack#1]
What should this project do? Some ideas:

- Calculator
- Array flipper (abcde > edcba)
- Some kind of algorithm that needs to store numbers for a later use and repeat.

**Comment by Cyberzoid1** [comment]
I'd vote for a calculator. probably just the basic operators
+,-,*,/,^,

We can also add order of operation a * (b + c) and/or variable assignment a = 4, a + 5...

Either way we need more of our teammates to pitch in. So far its only 2/7

**Comment by tsonnen** [comment]
I like the RPN calculator as well
The code that I put up is just boilerplate stack for us to go off of

**Comment by Cyberzoid1** [comment]
Had another idea. We could create a Rock Paper Scissors game where you load up say 10 choices in stack A, then someone else loads up 10 choices in stack B.
Next the program pops a choice off each stack then see's who won & tallies the score.

**Comment by Cyberzoid1** [comment]
Since nobody, except 1, contributed to this discussion so I went and added a Rock Paper Scissors game.

Adds a single function call in main `LetsPlayRockPaperScissors()`
