### ISSUE TITLE
LinkedList::PrintNode() printing address not contents

### ISSUE THREAD

**Issue by Cyberzoid1** [CS383Team2/CS383Stack#2]
The following fuction in linkedList.cpp prints the pointer address not value
```` c++
void LinkedList::PrintNode(){
    NodePtr p = head;
    while(p != NULL){
        cout << p << endl;
        p = p->next;
    }
}
````

Output 
````
./a.out
Pushing integers onto iStack
0 1 2 3 4 
Contents of iStack
0x245d090
0x245d070
0x245d050
0x245d030
0x245d010

Popping integers from iStack
4 3 2 1 0 
The stack is empty
````

I'll take a look at this later tonight but I believe the solution would be 
`cout << p->info <, endl;`

**Comment by tsonnen** [comment]
Sorry about that, this code is from 121. I just checked if it compiled.
Should be fixed in the most recent commit

**Comment by Cyberzoid1** [comment]
Thats fine. Just Identified an issue and created an issue report so it can get fixed in the future.

Also practice making an issue report
