### ISSUE TITLE
Location for Team discussion

### ISSUE THREAD

**Issue by Cyberzoid1** [CS383Team2/CS383Stack#4]
We should find a place or service where the team can correspond with each other.
Besides making issue reports :)
Issue reports are great for a targeted purpose/feature/or bug and such.

Some places to look into:
- Projects adds a sort of note wall
- Somewere on git there has to be a chat program
- Use an Integration such as slack since it integrates with github https://github.com/integrations/slack
- Use an external service such as discord or skype,

**Comment by tsonnen** [comment]
I agree. I have personally used:

- Slack
- Trello (Bulletin board service, allows you to assign people to tasks, actually kinda nice)

I do think that our current priority should be to get everyone on GitHub as I think we currently have 4/7.

**Comment by gjcarter** [comment]
Have used Trello a bit and second it. Really nice layout and easy to organize tasks and work needed to be done. Not sure if it has a general chat feature or something of that matter for quick communication.

**Comment by Cyberzoid1** [comment]
I dont have anything against trello although from the homepage it doesnt seem much different than projects. Check out this testProject https://github.com/orgs/CS383Team2/projects/1

I would personally prefer we pick one of these services (in order)
- Slack
- Discord
- Skype
- Curse voice
- Even a FB group would/maybe work
The first 3 I already use for coordinating with other groups. Slack and Discord possibly being the best.

**Comment by YupHio** [comment]
Discord seems to be working well. Now if I can just figure out GitHub...

**Comment by Cyberzoid1** [comment]
I'm sure you'll Git it
sorry :D
